"use client";
import { useEffect, useState } from 'react';
import { Compass, Phone, Menu, X, MapPin, Waves, Check } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import Lenis from 'lenis';
import 'lenis/dist/lenis.css';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
const old = 'https://www.sunseekercruisers.co.uk';
const offers = [
 {title:'Wave Leasing',tag:'YOUR TIME ON THE WATER',sub:'A new way to enjoy a Sunseeker',url:'/wave-lease',img:'yacht-transparent.png'},
 {title:'Lease Options',tag:'FIND YOUR PERFECT FIT',sub:'Explore the available options',url:'/lease-option',img:'yacht-transparent.png'},
 {title:'Moorings',tag:'A PLACE TO CALL YOURS',sub:'Discover UK & European moorings',url:'/moorings',img:'yacht-transparent.png'},
 {title:'Skippers & Support',tag:'CRUISE WITH CONFIDENCE',sub:'Get to know the people on board',url:'/rya---skippers-list',img:'yacht-transparent.png'},
];
function Choice({label,value,onChange,items}:{label:string,value:string,onChange:(s:string)=>void,items:string[]}) {return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i} value={i}>{i}</SelectItem>)}</SelectContent></Select>}
export default function Home(){
 const [menu,setMenu]=useState(false);const [experience,setExperience]=useState('Wave Leasing');const [region,setRegion]=useState('UK & Europe');const [timing,setTiming]=useState('Flexible dates');
 useEffect(() => {
  const media = window.matchMedia('(prefers-reduced-motion: reduce)');
  let lenis: Lenis | undefined;
  const configure = () => { lenis?.destroy(); lenis = undefined; if (!media.matches) lenis = new Lenis({ autoRaf: true, anchors: { offset: -24 }, lerp: 0.09, smoothWheel: true, syncTouch: false, allowNestedScroll: true }); };
  configure(); media.addEventListener('change', configure);
  return () => { lenis?.destroy(); media.removeEventListener('change', configure); };
 }, []);
 useEffect(() => { const escape = (e: KeyboardEvent) => { if(e.key === 'Escape') setMenu(false); }; window.addEventListener('keydown',escape); return () => window.removeEventListener('keydown',escape); }, []);
 const enquiry=`mailto:Hello@sunseekercruisers.co.uk?subject=${encodeURIComponent('My Sunseeker enquiry — '+experience)}&body=${encodeURIComponent('Hello Sunseeker Cruisers,\n\nI would like to find out more about '+experience+'.\nPreferred cruising area: '+region+'\nTiming: '+timing+'\n\nPlease contact me with the available options.\n\nName:\nPhone:')}`;

 return <main id="top">
  <section className="hero">
   <img className="hero-image" src="/images/hero.webp" alt="Luxury motor yacht on clear turquoise water" fetchPriority="high"/>
   <header className="header"><a href="#top" className="brand" aria-label="Sunseeker Cruisers home"><span className="brand-symbol"><Waves size={25}/></span><span>SUNSEEKER <small>CRUISERS</small></span></a><a className="header-discover" href="#about">Discover the possibilities</a><div className="header-actions"><a href="tel:+447817610000" aria-label="Call Sunseeker Cruisers"><Phone size={19}/></a><button onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?'Close navigation':'Open navigation'}>{menu?<X/>:<Menu/>}</button></div></header>
   {menu&&<nav className="mobile-menu">{[['Our story','#about'],['Wave Leasing','#possibilities'],['Your journey','#journey'],['Get in touch','#contact']].map(([t,u])=><a key={t} href={u} onClick={()=>setMenu(false)}>{t}</a>)}</nav>}
   <div className="hero-titles"><h1><span>Where</span>Extraordinary</h1><p>Adventures<br/><span>Begin.</span></p></div><p className="hero-kicker">A NEW WAVE OF SUNSEEKER YACHTING</p>
   <div className="hero-bottom"><p>Ever dreamed of cruising the open seas{' '}<br/>in your own Sunseeker?{' '}<br/><strong>Now you can, with Wave Leasing.</strong></p><a className="hero-card" href="#possibilities"><img src="/images/original-yacht.jpg" alt="Sunseeker cruiser from the original website"/><span>YOUR NEXT CHAPTER</span><b>Discover Wave Leasing</b></a></div>
   <div className="finder"><span className="finder-title"><Compass size={20}/> Your next adventure</span><Choice label="Experience" value={experience} onChange={setExperience} items={['Wave Leasing','Lease Options','Moorings','Skipper Support']}/><Choice label="Cruising area" value={region} onChange={setRegion} items={['UK & Europe','United Kingdom','Europe','Help me choose']}/><Choice label="Timing" value={timing} onChange={setTiming} items={['Flexible dates','This year','Next year','Just exploring']}/><a className="button light" href={enquiry}>Make an enquiry</a></div>
  </section>
  <section className="intro" id="about"><div className="section-heading reveal"><span className="eyebrow">THE SUNSEEKER CRUISERS WAY</span><h2>Your Sunseeker. Your time.<br/>A new wave of possibility.</h2><p>The open sea has always called. Wave Leasing offers a different way to answer — bringing the experience of a Sunseeker within reach, with time on the water to make your own.</p></div>
   <div className="story-row reveal"><div className="story-picture tilt-left"><img src="/images/advisor.webp" alt="Yacht advisor reviewing documents on deck" loading="lazy"/></div><div className="story-copy"><span className="tiny-number">01 / THE DREAM</span><h3>For the dreamers.</h3><p>Ever imagined heading out on your own Sunseeker? Discover the idea behind Wave Leasing, and a new way to enjoy the freedom of the open sea.</p><a className="text-link" href={old+'/how-it-works'}>Discover our story</a></div></div>
   <div className="story-row reverse reveal"><div className="story-copy"><span className="tiny-number">02 / THE POSSIBILITY</span><h3>For the doers.</h3><p>Explore Wave Leasing and the options available to you. From your first questions to finding your time on board, your next chapter starts here.</p><a className="text-link" href={old+'/lease-option'}>Explore lease options</a></div><div className="story-picture tilt-right"><img src="/images/cruising.jpg" alt="A Sunseeker on crystal-clear water" loading="lazy"/></div></div>
   <img className="statement-yacht reveal" src="/images/yacht-transparent.png" alt="Illustrative luxury motor yacht" loading="lazy"/>
  </section>
  <section className="possibilities section-pad" id="possibilities"><div className="section-heading reveal"><span className="eyebrow">EMBARK WITH US</span><h2>Your way to the water.</h2></div><div className="offer-grid">{offers.map((o,i)=><a className={'offer reveal offer-'+i} key={o.title} href={old+o.url}><div className="offer-art"><span className="offer-tag">{o.tag}</span><div className="arched-sea"/><img src={'/images/'+o.img} alt={o.title==='Wave Leasing'?'Sunseeker cruiser':'Illustrative motor yacht'} loading="lazy"/></div><div className="offer-info"><h3>{o.title}</h3><p><MapPin size={15}/>{o.sub}</p></div></a>)}</div><p className="image-note">Yacht imagery is illustrative. Speak with us about available boats and lease arrangements.</p></section>
  <section className="captain section-pad" id="journey"><div className="section-heading reveal"><h2>You’re in the<br/>captain’s seat.</h2><p>Your dream of the sea. A journey that starts with you.</p></div><Tabs defaultValue="leasing" className="journey-tabs"><TabsList className="tab-list"><TabsTrigger value="leasing">Wave Leasing</TabsTrigger><TabsTrigger value="support">Onboard support</TabsTrigger></TabsList><TabsContent value="leasing"><div className="journey-card"><div><span className="eyebrow">MAKE IT YOURS</span><h3>Find your way to<br/>a Sunseeker.</h3><p>A new approach to enjoying time on the water. Discover how Wave Leasing works and choose the next step that feels right for you.</p><ul><li><Check/>Explore the Wave Leasing approach</li><li><Check/>Discover the lease options</li><li><Check/>Talk through your plans with our team</li></ul><a className="button dark" href={old+'/wave-lease'}>Explore Wave Leasing</a></div><img src="/images/yacht-transparent.png" alt="Illustrative white luxury yacht" loading="lazy"/></div></TabsContent><TabsContent value="support"><div className="journey-card"><div><span className="eyebrow">CONFIDENCE ON BOARD</span><h3>More time for<br/>the open sea.</h3><p>Explore the practical side of your journey, from moorings to maintenance and skipper information.</p><ul><li><Check/>UK & European moorings</li><li><Check/>Maintenance information</li><li><Check/>RYA & skipper resources</li></ul><a className="button dark" href={old+'/rya---skippers-list'}>Meet your skipper</a></div><img src="/images/yacht-transparent.png" alt="Illustrative luxury motor yacht" loading="lazy"/></div></TabsContent></Tabs></section>
  <section className="journal section-pad"><div className="section-heading reveal"><span className="eyebrow">A LITTLE MORE INSPIRATION</span><h2>A new perspective.</h2><p>Everything you need to begin your Sunseeker story.</p></div><div className="journal-grid">{[{title:'What’s it all about?',text:'A voice said there has to be a way. Discover the story behind Wave Leasing.',img:'advisor.webp',url:'/how-it-works'},{title:'A new wave of yachting.',text:'Explore a different approach to your time on board with Wave Leasing.',img:'hero.webp',url:'/wave-lease'},{title:'Your place by the water.',text:'Discover mooring information and possibilities in the UK and Europe.',img:'beach.webp',url:'/moorings'}].map(x=><a href={old+x.url} className="journal-card reveal" key={x.title}><img src={'/images/'+x.img} alt={x.title} loading="lazy"/><div><h3>{x.title}</h3><p>{x.text}</p><span className="text-link">Read more</span></div></a>)}</div></section>
  <section className="life"><div className="section-heading reveal"><span className="eyebrow">FOLLOW THE FEELING</span><h2>Life on the water. In real time.</h2><p>Unhurried mornings. Open horizons. Your next great memory.</p></div><div className="gallery-strip"><img src="/images/beach.webp" alt="Coastal inspiration" loading="lazy"/><img src="/images/advisor.webp" alt="Life on deck" loading="lazy"/><img src="/images/hero.webp" alt="A yacht on turquoise seas" loading="lazy"/><img src="/images/cruising.jpg" alt="Sunseeker yacht inspiration" loading="lazy"/><img src="/images/original-yacht.jpg" alt="Sunseeker cruiser" loading="lazy"/></div><a className="text-link gallery-link" href={old+'/gallery'}>Explore the gallery</a></section>
  <footer id="contact"><div className="footer-scene"><img src="/images/beach.webp" alt="Aerial view of a yacht near a golden beach" loading="lazy"/></div><div className="footer-base"><div className="footer-grid"><div><a className="brand footer-brand" href="#top"><Waves/><span>SUNSEEKER<small>CRUISERS</small></span></a><p>The new wave of Sunseeker yachting.<br/>Now you can engage in your dreams.</p></div><div><h4>Explore</h4><a href={old+'/how-it-works'}>Our story</a><a href={old+'/wave-lease'}>Wave Leasing</a><a href={old+'/lease-option'}>Lease options</a></div><div><h4>Your journey</h4><a href={old+'/moorings'}>Moorings</a><a href={old+'/maintenance'}>Maintenance</a><a href={old+'/rya---skippers-list'}>RYA & skippers</a></div><div><h4>Get in touch</h4><a href="tel:+447817610000">+44 (0) 7817 610000</a><a href="mailto:Hello@sunseekercruisers.co.uk">Hello@sunseekercruisers.co.uk</a><p>UK Office: New Brighton CH45 2PP<br/>World Trade Centre, 6 Bayside Road<br/>Gibraltar GX11 1AA</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Sunseeker Cruisers</span><a href={old+'/privacy'}>Privacy policy</a><a href="#top">Back to top</a></div></div></footer>
 </main>
}
